Remove references to k_pipe_block_put
zephyrproject-rtos/percepio pull request #4
Opened 2023-10-01 17:16 UTC by peter-mitsis

The routine k_pipe_block_put() was removed years ago. There is no need to keep references to it.

2023-10-05 20:24 UTC, nashif approved these changes

2023-10-10 11:23 UTC, aronlander-pe requested changes
Should be fine, except for the part commented

2023-10-10 11:23 UTC, aronlander-pe commented on TraceRecorder/kernelports/Zephyr/include/trcKernelPort.h
> -#define PSF_EVENT_PIPE_BLOCK_PUT_ENTER						0xDA
Instead of removing these, could you please rename them to: "PSF_EVENT_PIPE_BLOCK_PUT_ENTER_DEPRECATED" and "PSF_EVENT_PIPE_BLOCK_PUT_EXIT_DEPRECATED"? The reason to why we would want to do this is due to compatibility between older versions of Zephyr and Tracealyzer. This is due to that removing these would require a format version bump (these will be removed in a later release).

2023-10-10 17:15 UTC, peter-mitsis commented on TraceRecorder/kernelports/Zephyr/include/trcKernelPort.h
> -#define PSF_EVENT_PIPE_BLOCK_PUT_ENTER						0xDA
@aronlander-pe - As per your request, I renamed them instead of removing them.

2023-10-11 07:46 UTC, aronlander-pe approved these changes
Looks great, approving this.

2023-10-11 10:26 UTC, eriktamlin approved these changes

2023-10-11 10:27 UTC, merged